#ifndef XLAYOUTDISPLAYS_EDIDCONSTS_H
#define XLAYOUTDISPLAYS_EDIDCONSTS_H

#define EDID_LENGTH 256

#define EDID_MAX_CM_HORIZ 0x15
#define EDID_MAX_CM_VERT 0x16

#endif //XLAYOUTDISPLAYS_EDIDCONSTS_H
